steps:

#
# Extract the cache
#
# The gradle build cache is stored as a tarball in Google Cloud Storage to
# make builds faster.
#
# After extracting the cache to the /build_cache directory, we need to supply
# that to gradle, and include the volume in steps that require the cache.

#
#
#
#


#
# Build the project
#

- name: 'gcr.io/ytmobileplayer/android:30-ndk-r17b'
  id: build
  args: ["./gradlew"]
  env:
  - 'TERM=dumb'
  - 'JAVA_TOOL_OPTIONS="-Xmx3g"'
  - 'GRADLE_USER_HOME=/build_cache/.gradle'
  - 'GRADLE_OPTS="-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=32 -Dkotlin.incremental=false -Dorg.gradle.caching=true"'
  - 'BRANCH_NAME=$BRANCH_NAME'

#
# Run test
#
#- name: 'gcr.io/contbuild-263903/android:29-ndk-r17b-jre11'
  #  id: test
  #args: ["./gradlew", "test"]
    #env:
    #- 'TERM=dumb'
  #- 'JAVA_TOOL_OPTIONS="-Xmx3g"'
  #- 'JAVA_HOME=/usr/lib/jvm/jdk-11'
  #- 'GRADLE_USER_HOME=/build_cache/.gradle'
  #- 'GRADLE_OPTS="-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=32 -Dkotlin.incremental=false -Dorg.gradle.caching=true"'
  #- 'BRANCH_NAME=$BRANCH_NAME'
  #dir: 'releaseParserProj'

#
# Vol
#

# Set a persistent volume according to /cloud-build/docs/build-config (search for volumes)
- name: 'ubuntu'
  volumes:
  - name: 'vol1'
    path: '/persistent_volume'
  args: ['cp', '-a', '.', '/persistent_volume']


#
# Make APK
#

- name: 'gcr.io/cloud-builders/docker'
  volumes:
  - name: 'vol1'
    path: '/persistent_volume'
  args: ['run', '-v', 'vol1:/home/app', '--rm', 'gcr.io/ytmobileplayer/gradle', '/bin/sh', '-c', 'cd /home/app && ./gradlew clean assembleDebug']


# Push the APK Output from vol1 to your GCS Bucket with Short Commit SHA.
- name: 'gcr.io/cloud-builders/gsutil'
  volumes:
  - name: 'vol1'
    path: '/persistent_volume'
  args: ['cp', '/persistent_volume/app/build/outputs/apk/debug', 'gs://ytpobileplayer-artifact']


#
# Save the Jar
#

#- name: 'gcr.io/cloud-builders/gsutil'
 # args: ['-q', 'cp', '-r', './app/build/outputs/apk/debug', 'gs://ytpobileplayer-artifact']
  #waitFor: ['build']

  
#
# Save the test results
#
  #- name: 'gcr.io/cloud-builders/gsutil'
  #args: ['-q', 'cp', '-r', 'releaseParserProj/build/reports/tests/test/index.html', 'gs://parser-jar-artifacts']
  #waitFor: ['test']

# Option
#
timeout: 1800s
